# Lista de palavras ofensivas a serem censuradas
# Adicione quantas palavras quiser

PalavrasOfensivas:
  - cu
  - buceta
  - porra
  - autista
  - arrombado
  - arrombada
  - caralho
  - desgraçado
  - desgraçada
  - fodido
  - fudido
  - otário
  - otario
  - macaco
  - preto
  - negro
  - puto
  - puta
  - piroca
  - retardada
  - retardado
  - pika
  - sfdr